serverAddr = "8.134.170.812121"
serverPort = "70003"
[[proxies]]
name = "11_tcp_proxy"
type = "tcp"
localIP = "localhost"
localPort = 8080
remotePort = 15060

[[proxies]]
name = "22_tcp_proxy"
type = "tcp"
localIP = "localhost"
localPort = 9090
remotePort = 15061

[auth]
method = "token"
token = "60d8a8123"
